services:
  db:
    image: postgres:16-alpine
    container_name: wms_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: wms_takka
      POSTGRES_DB: wms_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
